
include: package:lint/strict.yaml 

analyzer:
  exclude:
    #- '**.freezed.dart'
    #- '**.g.dart'

# https://dart-lang.github.io/linter/lints/options/options.html
linter:
  rules:
    avoid_classes_with_only_static_members: false
    always_declare_return_types: true
    sort_constructors_first: true
    prefer_single_quotes: true
    lines_longer_than_80_chars: true