name: portfolio
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_analytics: ^10.4.3
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_storage: ^11.2.3

  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
  uses-material-design: true